#ifndef SCT_CONFIG_H_

#define WIFI_SSID "SCT"
#define WIFI_PASSWORD "12345678"

#define WIFI_STATION_SSID "Sample"
#define WIFI_STATION_PASSWORD ""

#define WIFI_SOFTAP_CONNECTION_MAX_RETRY 5

#define DEFAULT_VREF 1100

#define PULL_DOWN_RESISTOR_OM 15200
#define DEFAULT_RESISTOR_OM (0 + PULL_DOWN_RESISTOR_OM)

#define MAX_FILES_AMOUNT 10

#define SCRATCH_BUFSIZE 8192

#endif