#ifndef SCT_CONFIG_H_

#define WIFI_SSID "SCT"
#define WIFI_PASSWORD "12345678"

#define WIFI_STATION_SSID ""
#define WIFI_STATION_PASSWORD ""

#define DAC_CHNL DAC_CHANNEL_1
#define ADC_CHNL ADC_CHANNEL_7

#define DEFAULT_VREF 1100

#define DEFAULT_RESISTOR_OM 41500

#define MAX_FILES_AMOUNT 10

#define SCRATCH_BUFSIZE 8192

#endif
